language: php
sudo: true

php:
  - 5.6
  - 7.0

notifications:
 slack: exteamc:5mDwsT0TToX71OLtnFgtpPyO
 email: never

services: mysql

install:
  # create a new database for the hyn connection
  - export DB_CONNECTION=sqlite QUEUE_DRIVER=sync APP_ENV=testing CACHE_DRIVER=array SESSION_DRIVER=array

script:
  #script to setup the package for testing
  - composer update
  - php artisan vendor:publish --force
  - phpunit
